### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [yk-saito/hotel-booking-dapp#31]
- [x] 提出物が学習コンテンツ通りに作成されているかの動作確認ができる、テストスクリプトを追加する
- [x] https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by uukait** [comment]
`codebuild`上での動作確認OKです！
- [build run log](https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/733910873054/projects/stg-codetest/build/stg-codetest%3A3676b310-e7ce-4fd7-8f44-965bf8e30a7f/log?region=ap-northeast-1)

**Comment by neila** [comment]
lgtm
